alias g='git'
alias gl='git pull'
alias gp='git push'
alias gm='git merge'
alias gs='git status'
alias gh='git log'
alias ga='git add'
alias gaa='git add --all'
alias gd='git diff'
alias gdc='git diff --cached'
alias gc='git commit'
alias gcam='git commit --all --message'
alias gco='git checkout'
alias gct='git checkout --track'
alias gcb='git checkout -b'
alias grv='git remote --verbose'
alias gb='git branch'
alias gbd='git branch --delete'
alias gba='git branch --all'
alias gbv='git branch -vv'

alias d='docker'
alias dp='docker ps'
alias dpa='docker ps --all'
alias dil='docker image ls'

alias v='nvim'

alias k="${HOME}/src/virtualization-tools/bin/kubernetes/kubectl.sh"
alias ku="${HOME}/src/virtualization-tools/bin/kubernetes/set-cluster.sh"
